In [ ]:
#c.c. = complex conjugate
#i = I*iCPV in mathematica = 1j in python
#coefficient not equal by manual and mathematica code? I believe the code then. 

In [3]:
#einsum & function for 4d-tensor
import numpy as np
x = np.arange(81)
WC = x.reshape((3, 3, 3, 3))
#y = np.arange(9)
#G = y.reshape((3,3))
G = np.matrix('1 2 3; 4 5 6; 7 8 9')

#np.einsum("rpts,pt", WC,G)
#np.einsum("rstt", WC)
np.trace(WC)

array([[108, 111, 114],
       [117, 120, 123],
       [126, 129, 132]])

In [21]:
#conj
import numpy as np
G = np.matrix('1 2 3; 4 5 6; 7 8 9')
G = G+1j*G
np.conj(G)

matrix([[ 1.-1.j,  2.-2.j,  3.-3.j],
        [ 4.-4.j,  5.-5.j,  6.-6.j],
        [ 7.-7.j,  8.-8.j,  9.-9.j]])

In [21]:
#kronecker delta for 2d-tensor
import numpy as np
x = np.arange(9)
x = x.reshape((3,3))
y = np.identity(3)
np.multiply(x,y)

array([[ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  8.]])