In [ ]:
#c.c. = complex conjugate
#i = I*iCPV in mathematica = 1j in python
#coefficient not equal by manual and mathematica code? I believe the code then. 

In [3]:
#einsum & function for 4d-tensor
import numpy as np
x = np.arange(81)
WC = x.reshape((3, 3, 3, 3))
y = np.arange(9)
G2 = y.reshape((3,3))
G = np.matrix('1 2 3; 4 5 6; 7 8 9')

#np.einsum("rpts,pt", WC,G)
#np.einsum("rstt", WC)
#np.trace(WC)
#np.einsum("sv,tw,prvw", G, G2, WC)
np.einsum("prts", WC)
np.einsum("pt", G)   #...why?

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#4d/2d*2d delta
import numpy as np
I3 = np.identity(3)
x = np.arange(81)
WC = x.reshape((3, 3, 3, 3))
y = np.arange(9)
G = y.reshape((3,3))

np.einsum("rs,pt", G, I3)
#np.einsum("prww,st", WC, I3)

array([[[[ 0.,  0.,  0.],
         [ 1.,  0.,  0.],
         [ 2.,  0.,  0.]],

        [[ 3.,  0.,  0.],
         [ 4.,  0.,  0.],
         [ 5.,  0.,  0.]],

        [[ 6.,  0.,  0.],
         [ 7.,  0.,  0.],
         [ 8.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  1.,  0.],
         [ 0.,  2.,  0.]],

        [[ 0.,  3.,  0.],
         [ 0.,  4.,  0.],
         [ 0.,  5.,  0.]],

        [[ 0.,  6.,  0.],
         [ 0.,  7.,  0.],
         [ 0.,  8.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0.,  0.,  2.]],

        [[ 0.,  0.,  3.],
         [ 0.,  0.,  4.],
         [ 0.,  0.,  5.]],

        [[ 0.,  0.,  6.],
         [ 0.,  0.,  7.],
         [ 0.,  0.,  8.]]]])

In [21]:
#conj
import numpy as np
G = np.matrix('1 2 3; 4 5 6; 7 8 9')
G = G+1j*G
np.conj(G)

matrix([[ 1.-1.j,  2.-2.j,  3.-3.j],
        [ 4.-4.j,  5.-5.j,  6.-6.j],
        [ 7.-7.j,  8.-8.j,  9.-9.j]])

In [21]:
#kronecker delta for 2d-tensor
import numpy as np
x = np.arange(9)
x = x.reshape((3,3))
y = np.identity(3)
np.multiply(x,y)

array([[ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  8.]])